server:
  port: ${CONTAINER_PORT}

eureka:
  instance:
    preferIpAddress: true
    hostname: todoserviceregistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




