apiVersion: v1
kind: Service
metadata:
  namespace: todo-cn-app
  name: todocommandservice
  labels:
    app: todocommandservice
spec:
  type: NodePort
  ports:
  - port: 9084
    name: todocommandservice
    targetPort: 9084
  selector:
    app: todocommandservice
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: todo-cn-app
  name: todocommandservice
  labels:
    app: todocommandservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todocommandservice
  template:
    metadata:
      labels:
        app: todocommandservice
    spec:
      containers:
      - name: todocommandservice
        image: mirna/todocommandservice
        resources:
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 9084
        env:
        - name: EUREKA_URL
          value: "http://todoserviceregistry:8761/eureka"  

    
    