apiVersion: v1
kind: Service
metadata: 
  namespace: todo-cn-app
  name: todo-messaging
  labels: 
    name: todo-messaging
spec: 
  ports:
    # the port that this service should serve on
    - port: 5672
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: todo-messaging
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: todo-cn-app
  name: todo-messaging
  labels:
    app: todo-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-messaging
  template:
    metadata:
      labels:
        app: todo-messaging
    spec:
      containers:
      - name: rabbitmq
        image: tutum/rabbitmq:latest
        resources:
          requests:
            memory: "256Mi"
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_PASS
          value: admin
        - name: RABBITMQ_VHOST
          value: 192.168.99.100
        ports:
        - containerPort: 5672
          name: rabbitmq