spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin

server:
  port: 9084

    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true    